#include <stdio.h>
#include <stdlib.h>

#define INITIAL_CAPACITY 10
#define GROWTH_FACTOR 2

/*
This code is generated by chatgpt
*/

int get_line(char **line);
void copy(char *to, char *from);

int main() {
    int len;
    int max = 0;
    char *line = NULL;
    char *longest = NULL;

    while ((len = get_line(&line)) > 0) {
        if (len > max) {
            max = len;
            if (longest != NULL) {
                free(longest);
            }
            longest = line;
            line = NULL;
        } else {
            free(line);
            line = NULL;
        }
    }

    if (max > 0) {
        printf("%s", longest);
    }

    free(longest);
    longest = NULL;

    return 0;
}

int get_line(char **line) {
    int c;
    int i = 0;
    int capacity = INITIAL_CAPACITY;

    *line = (char *)malloc(capacity * sizeof(char));
    if (*line == NULL) {
        printf("Memory allocation failed.\n");
        exit(1);
    }

    while ((c = getchar()) != EOF && c != '\n') {
        (*line)[i] = c;
        i++;

        if (i >= capacity) {
            capacity *= GROWTH_FACTOR;
            char *temp = (char *)realloc(*line, capacity * sizeof(char));
            if (temp == NULL) {
                printf("Memory allocation failed.\n");
                exit(1);
            }
            *line = temp;
        }
    }

    (*line)[i] = '\0';
    return i;
}

void copy(char *to, char *from) {
    int i = 0;

    while ((to[i] = from[i]) != '\0') {
        ++i;
    }
}
